import { useEffect, useState } from 'react';
import PageLayout from '../../components/PageLayout';
import LoadingSpinner from '../../components/LoadingSpinner';
import EmptyState from '../../components/EmptyState';
import api from '../../services/api';
import toast from 'react-hot-toast';

function parseCsv(csv) { return csv.trim().split(/\r?\n/).map((line) => line.split(/,(?=")|,(?!")/).map((value) => value.replace(/^"|"$/g, '').replaceAll('""', '"'))); }

export default function AttendanceReport() {
  const now = new Date(); const [classes, setClasses] = useState([]); const [classSectionId, setClassSectionId] = useState(''); const [month, setMonth] = useState(now.getMonth() + 1); const [year, setYear] = useState(now.getFullYear()); const [rows, setRows] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api.get('/teacher/classes').then(({ data }) => { setClasses(data.data); setClassSectionId(data.data[0]?._id || ''); }).catch((err) => setError(err.response?.data?.message || 'Unable to load classes')); }, []);
  async function loadReport() { setLoading(true); setError(''); try { const { data } = await api.get('/teacher/reports/attendance', { params: { classSectionId, month, year }, responseType: 'text' }); setRows(parseCsv(data)); toast.success('Report preview loaded'); } catch (err) { const message = err.response?.data?.message || 'Unable to load report'; setError(message); toast.error(message); } finally { setLoading(false); } }
  async function download() { try { const { data } = await api.get('/teacher/reports/attendance', { params: { classSectionId, month, year }, responseType: 'blob' }); const url = URL.createObjectURL(data); const link = document.createElement('a'); link.href = url; link.download = 'attendance-report.csv'; link.click(); URL.revokeObjectURL(url); toast.success('CSV download started'); } catch (err) { const message = err.response?.data?.message || 'Unable to download report'; setError(message); toast.error(message); } }
  return <PageLayout><div className="mb-8"><p className="text-sm font-semibold text-blue-600">Teacher reports</p><h1 className="page-title mt-1">Monthly attendance report</h1></div><div className="panel mb-6"><div className="grid gap-4 md:grid-cols-4"><select className="field" onChange={(event) => setClassSectionId(event.target.value)} value={classSectionId}><option value="">Select class</option>{classes.map((item) => <option key={item._id} value={item._id}>{item.grade} - {item.section}</option>)}</select><select className="field" onChange={(event) => setMonth(Number(event.target.value))} value={month}>{Array.from({ length: 12 }, (_, index) => <option key={index + 1} value={index + 1}>{new Date(2000, index).toLocaleString('default', { month: 'long' })}</option>)}</select><input className="field" max="2100" min="2000" onChange={(event) => setYear(Number(event.target.value))} type="number" value={year} /><div className="flex gap-2"><button className="button-primary" disabled={!classSectionId || loading} onClick={loadReport} type="button">{loading ? 'Loading...' : 'Preview'}</button><button className="button-secondary" disabled={!classSectionId} onClick={download} type="button">Download CSV</button></div></div></div>{error && <p className="error-message">{error}</p>}<div className="panel overflow-x-auto">{loading ? <LoadingSpinner /> : rows.length ? <table className="data-table min-w-[780px]"><thead><tr>{rows[0].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{rows.slice(1).map((row, index) => <tr key={index}>{row.map((value, cellIndex) => <td key={cellIndex}>{value}</td>)}</tr>)}</tbody></table> : <EmptyState title="No report preview" message="Choose a class and period, then select Preview." />}</div></PageLayout>;
}