import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import DashboardCard from '../../components/DashboardCard';
import EmptyState from '../../components/EmptyState';
import LoadingSpinner from '../../components/LoadingSpinner';
import PageLayout from '../../components/PageLayout';
import StatCard from '../../components/StatCard';
import api from '../../services/api';

export default function Dashboard() {
  const [classes, setClasses] = useState([]); const [classSectionId, setClassSectionId] = useState(''); const [data, setData] = useState(null); const [alerts, setAlerts] = useState([]); const [error, setError] = useState('');
  useEffect(() => { api.get('/teacher/classes').then(({ data: response }) => { setClasses(response.data); setClassSectionId(response.data[0]?._id || ''); }).catch((err) => setError(err.response?.data?.message || 'Unable to load classes')); }, []);
  useEffect(() => { if (classSectionId) Promise.all([api.get('/teacher/dashboard', { params: { classSectionId } }), api.get('/teacher/attendance/alerts', { params: { classSectionId } })]).then(([dashboardResponse, alertResponse]) => { setData(dashboardResponse.data.data); setAlerts(alertResponse.data.data); }).catch((err) => setError(err.response?.data?.message || 'Unable to load dashboard')); }, [classSectionId]);
  const selectedClass = classes.find((item) => item._id === classSectionId);
  return <PageLayout><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="overview-kicker">Teacher overview</p><h1 className="overview-title">Today in your classroom</h1><p className="mt-2 text-xs text-[#5B7590]">{data?.date || 'Select a class'}{selectedClass ? ` · ${selectedClass.grade} - ${selectedClass.section}` : ''}</p></div><select className="field max-w-xs" onChange={(event) => setClassSectionId(event.target.value)} value={classSectionId}><option value="">Select class</option>{classes.map((item) => <option key={item._id} value={item._id}>{item.grade} - {item.section}</option>)}</select></div>{error && <p className="error-message">{error}</p>}{!data && !error ? <LoadingSpinner /> : data ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Present" tone="green" value={data.attendanceSummary.present} detail={`${data.totalStudents} students enrolled`} /><StatCard label="Absent" tone="red" value={data.attendanceSummary.absent} /><StatCard label="Late" tone="yellow" value={data.attendanceSummary.late} /><StatCard label="Leave" tone="purple" value={data.attendanceSummary.leave} /></div>{alerts.length > 0 && <DashboardCard title="Students needing attention"><div className="space-y-3">{alerts.map((item) => <div className="rounded-lg border border-[#F4DCA7] bg-[#FDF0D5] px-3 py-2" key={item.studentId}><p className="text-sm font-semibold text-[#0B1F3A]">{item.name}</p><p className="mt-1 text-xs text-[#8A5300]">{item.warnings.join(' · ')}</p></div>)}</div></DashboardCard>}<DashboardCard title="Pending leave requests"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-3xl font-medium text-[#0B1F3A]">{data.pendingLeaveRequests}</p><p className="mt-1 text-sm text-[#5B7590]">Requests waiting for your review</p></div><div className="flex flex-wrap gap-3"><Link className="button-primary" to="/teacher/attendance">Mark attendance</Link><Link className="button-secondary" to="/teacher/leave">Review leave</Link><Link className="text-sm font-semibold text-[#2563EB]" to="/teacher/reports/attendance">View reports →</Link></div></div></DashboardCard></> : <EmptyState />}</PageLayout>;
}