import { useEffect, useState } from 'react';
import LeaveTable from '../../components/LeaveTable';
import api from '../../services/api';

const tabs = ['pending', 'approved', 'rejected'];

export default function LeaveRequests() {
  const [classes, setClasses] = useState([]); const [classSectionId, setClassSectionId] = useState(''); const [status, setStatus] = useState('pending'); const [leaves, setLeaves] = useState([]); const [balances, setBalances] = useState({}); const [remarks, setRemarks] = useState({}); const [overrides, setOverrides] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { api.get('/teacher/classes').then(({ data }) => { setClasses(data.data); setClassSectionId(data.data[0]?._id || ''); }).catch((err) => setError(err.response?.data?.message || 'Unable to load classes')).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!classSectionId) return; setLoading(true); api.get('/teacher/leave', { params: { classSectionId, status } }).then(({ data }) => setLeaves(data.data)).catch((err) => setError(err.response?.data?.message || 'Unable to load leave requests')).finally(() => setLoading(false)); }, [classSectionId, status]);
  useEffect(() => { if (!leaves.length) { setBalances({}); return; } Promise.all([...new Set(leaves.map((leave) => leave.studentId?._id).filter(Boolean))].map(async (studentId) => { const { data } = await api.get('/teacher/leave-balance', { params: { studentId } }); return [studentId, data.data]; })).then((entries) => setBalances(Object.fromEntries(entries))).catch((err) => setError(err.response?.data?.message || 'Unable to load leave balances')); }, [leaves]);
  async function review(leave, nextStatus) { try { const { data } = await api.patch(`/teacher/leave/${leave._id}`, { status: nextStatus, override: overrides[leave._id] === true, teacherRemarks: remarks[leave._id] || '' }); setLeaves(leaves.filter((item) => item._id !== leave._id)); setMessage(data.message); } catch (err) { setError(err.response?.data?.message || 'Unable to review leave request'); } }
  function actions(leave) { const balance = balances[leave.studentId?._id]?.find((item) => item.leaveType === leave.type); const remaining = balance?.remaining ?? 0; const exceeds = remaining < leave.requestedDays; const override = overrides[leave._id] === true; return <div className="flex min-w-52 flex-wrap gap-2">{exceeds && <><p className="w-full rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-700">This exceeds remaining balance ({remaining} days).</p><label className="flex w-full items-center gap-2 text-xs text-slate-600"><input checked={override} onChange={(event) => setOverrides({ ...overrides, [leave._id]: event.target.checked })} type="checkbox" />Approve with override</label></>}<input className="field" onChange={(event) => setRemarks({ ...remarks, [leave._id]: event.target.value })} placeholder="Optional remark" value={remarks[leave._id] || ''} /><button className="button-primary" disabled={exceeds && !override} onClick={() => review(leave, 'approved')} type="button">Approve</button><button className="button-secondary" onClick={() => review(leave, 'rejected')} type="button">Reject</button></div>; }
  return <section><div className="mb-6"><h2 className="page-title">Leave requests</h2><p className="page-subtitle">Review requests from students in your class.</p></div><div className="panel mb-6"><label className="text-sm font-semibold text-slate-700">Class<select className="field mt-2 max-w-md" onChange={(event) => setClassSectionId(event.target.value)} value={classSectionId}><option value="">Select class</option>{classes.map((item) => <option key={item._id} value={item._id}>{item.grade} - {item.section}</option>)}</select></label></div><div className="mb-4 flex gap-2 overflow-x-auto">{tabs.map((tab) => <button className={`rounded-lg px-4 py-2 text-sm font-semibold capitalize ${status === tab ? 'bg-indigo-600 text-white' : 'bg-white text-slate-600'}`} key={tab} onClick={() => setStatus(tab)} type="button">{tab}</button>)}</div>{message && <p className="success-message">{message}</p>}{error && <p className="error-message">{error}</p>}<div className="panel">{loading ? <p className="py-8 text-center text-slate-500">Loading leave requests...</p> : <LeaveTable actions={status === 'pending' ? actions : undefined} leaves={leaves} />}</div></section>;
}