import { useEffect, useState } from 'react';
import LeaveTable from '../../components/LeaveTable';
import api from '../../services/api';

const tabs = ['pending', 'approved', 'rejected'];

export default function LeaveRequests() {
  const [classes, setClasses] = useState([]); const [classSectionId, setClassSectionId] = useState(''); const [status, setStatus] = useState('pending'); const [leaves, setLeaves] = useState([]); const [remarks, setRemarks] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { api.get('/teacher/classes').then(({ data }) => { setClasses(data.data); setClassSectionId(data.data[0]?._id || ''); }).catch((err) => setError(err.response?.data?.message || 'Unable to load classes')).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!classSectionId) return; setLoading(true); api.get('/teacher/leave', { params: { classSectionId, status } }).then(({ data }) => setLeaves(data.data)).catch((err) => setError(err.response?.data?.message || 'Unable to load leave requests')).finally(() => setLoading(false)); }, [classSectionId, status]);
  async function review(leave, nextStatus) { try { const { data } = await api.patch(`/teacher/leave/${leave._id}`, { status: nextStatus, teacherRemarks: remarks[leave._id] || '' }); setLeaves(leaves.filter((item) => item._id !== leave._id)); setMessage(data.message); } catch (err) { setError(err.response?.data?.message || 'Unable to review leave request'); } }
  return <section><div className="mb-6"><h2 className="page-title">Leave requests</h2><p className="page-subtitle">Review requests from students in your class.</p></div><div className="panel mb-6"><label className="text-sm font-semibold text-slate-700">Class<select className="field mt-2 max-w-md" onChange={(event) => setClassSectionId(event.target.value)} value={classSectionId}><option value="">Select class</option>{classes.map((item) => <option key={item._id} value={item._id}>{item.grade} - {item.section}</option>)}</select></label></div><div className="mb-4 flex gap-2 overflow-x-auto">{tabs.map((tab) => <button className={`rounded-lg px-4 py-2 text-sm font-semibold capitalize ${status === tab ? 'bg-indigo-600 text-white' : 'bg-white text-slate-600'}`} key={tab} onClick={() => setStatus(tab)} type="button">{tab}</button>)}</div>{message && <p className="success-message">{message}</p>}{error && <p className="error-message">{error}</p>}<div className="panel">{loading ? <p className="py-8 text-center text-slate-500">Loading leave requests...</p> : <LeaveTable actions={status === 'pending' ? (leave) => <div className="flex min-w-52 flex-wrap gap-2"><input className="field" onChange={(event) => setRemarks({ ...remarks, [leave._id]: event.target.value })} placeholder="Optional remark" value={remarks[leave._id] || ''} /><button className="button-primary" onClick={() => review(leave, 'approved')} type="button">Approve</button><button className="button-secondary" onClick={() => review(leave, 'rejected')} type="button">Reject</button></div> : undefined} leaves={leaves} />}</div></section>;
}