import { useEffect, useState } from 'react';
import StatusToggle from '../../components/StatusToggle';
import LoadingSpinner from '../../components/LoadingSpinner';
import PageLayout from '../../components/PageLayout';
import TimetableGrid from '../../components/TimetableGrid';
import api from '../../services/api';

export default function TimetablePage() {
  const [timetable, setTimetable] = useState(null); const [selected, setSelected] = useState(null); const [records, setRecords] = useState([]); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { api.get('/teacher/timetable').then(({ data }) => setTimetable(data.data)).catch((err) => setError(err.response?.data?.message || 'Unable to load timetable')).finally(() => setLoading(false)); }, []);
  async function selectPeriod(period) { setSelected(period); setError(''); try { const { data } = await api.get('/teacher/attendance', { params: { classSectionId: period.classSectionId._id, date } }); setRecords(data.data.map((record) => ({ ...record, status: record.status === 'unmarked' ? 'present' : record.status }))); } catch (err) { setError(err.response?.data?.message || 'Unable to load class roster'); } }
  function updateStatus(studentId, status) { setRecords((current) => current.map((record) => record.studentId === studentId ? { ...record, status } : record)); }
  async function save() { setSaving(true); setMessage(''); setError(''); try { const { data } = await api.post('/teacher/attendance/period', { classSectionId: selected.classSectionId._id, date, periodNumber: selected.periodNumber, records: records.map(({ studentId, status }) => ({ studentId, status })) }); setMessage(data.message); } catch (err) { setError(err.response?.data?.message || 'Unable to save period attendance'); } finally { setSaving(false); } }
  return <PageLayout><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="overview-kicker">Teacher timetable</p><h1 className="overview-title">Open a period to mark attendance</h1></div><input className="field max-w-xs" onChange={(event) => setDate(event.target.value)} type="date" value={date} /></div>{message && <p className="success-message">{message}</p>}{error && <p className="error-message">{error}</p>}{loading ? <LoadingSpinner /> : <TimetableGrid onPeriodClick={selectPeriod} timetable={timetable || []} />}{selected && <div className="panel mt-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-medium">Period {selected.periodNumber} · {selected.subjectId?.name}</h2><p className="text-sm text-[#5B7590]">{selected.dayOfWeek} · {date}</p></div><button className="text-xl text-[#5B7590]" onClick={() => setSelected(null)} type="button">×</button></div><div className="overflow-x-auto"><table className="data-table min-w-[680px]"><thead><tr><th>Roll no</th><th>Student</th><th>Status</th></tr></thead><tbody>{records.map((record) => <tr key={record.studentId}><td>{record.rollNo}</td><td>{record.name}</td><td><StatusToggle onChange={(status) => updateStatus(record.studentId, status)} value={record.status} /></td></tr>)}</tbody></table></div><button className="button-primary mt-5" disabled={saving || !records.length} onClick={save} type="button">{saving ? 'Saving...' : 'Save period attendance'}</button></div>}</PageLayout>;
}