import { useState } from 'react';

const statusClasses = { present: 'border-[#BCEBE3] bg-[#DDF5F1] text-[#0F766E]', absent: 'border-[#F5C4CC] bg-[#FDE4E8] text-[#9F1F35]', late: 'border-[#F4DCA7] bg-[#FDF0D5] text-[#8A5300]', leave: 'border-[#D8D1F4] bg-[#ECE8FB] text-[#4C3BA8]', unmarked: 'border-[#E1ECF5] bg-[#F8FBFE] text-[#7A93AD]' };

export default function AttendanceCalendar({ days = [], month, year }) {
  const [selected, setSelected] = useState(null);
  const firstDay = new Date(Date.UTC(year, month - 1, 1)).getUTCDay();
  const blanks = Array.from({ length: (firstDay + 6) % 7 });
  return <section className="panel"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-medium text-[#0B1F3A]">{new Date(year, month - 1).toLocaleString('default', { month: 'long', year: 'numeric' })}</h2><div className="hidden gap-3 text-xs text-[#5B7590] sm:flex"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#14B8A6]" />Present</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#D9485F]" />Absent</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#F2A93B]" />Late</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#6D5BD0]" />Leave</span></div></div><div className="grid grid-cols-7 gap-2 text-center text-xs font-semibold text-[#5B7590]">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day) => <span key={day}>{day}</span>)}{blanks.map((_, index) => <span className="min-h-16" key={`blank-${index}`} />)}{days.map((day) => <button className={`min-h-16 rounded-lg border p-2 text-left transition hover:shadow-md ${statusClasses[day.status]}`} key={day.date} onClick={() => setSelected(day)} type="button"><span className="font-semibold">{Number(day.date.slice(-2))}</span><span className="mt-2 block text-[10px] capitalize">{day.status}</span></button>)}</div>{selected && <div className="fixed inset-0 z-20 flex items-center justify-center bg-[#0B1F3A]/40 p-6" onClick={() => setSelected(null)}><div className="w-full max-w-sm rounded-xl bg-white p-6 shadow-xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs text-[#5B7590]">Attendance detail</p><h3 className="mt-1 text-xl font-medium text-[#0B1F3A]">{selected.date}</h3></div><button className="text-xl text-[#5B7590]" onClick={() => setSelected(null)} type="button">×</button></div><p className={`status-pill status-${selected.status} mt-5`}>{selected.status}</p><p className="mt-4 text-sm text-[#5B7590]">This day is marked as {selected.status}.</p></div></div>}</section>;
}